[2025-02-28T18:25:23.419+0200] {processor.py:186} INFO - Started process (PID=93309) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:25:23.420+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T18:25:23.420+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:25:23.420+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:25:23.458+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:25:23.458+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T18:25:23.459+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:25:23.459+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T18:25:23.459+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:25:23.489+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-28T18:27:12.830+0200] {processor.py:186} INFO - Started process (PID=93738) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:27:12.831+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T18:27:12.832+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:27:12.832+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:27:12.874+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:27:12.874+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T18:27:12.874+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:27:12.874+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T18:27:12.874+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:27:12.907+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2025-02-28T18:29:53.846+0200] {processor.py:186} INFO - Started process (PID=94393) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:29:53.847+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T18:29:53.847+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:29:53.847+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:29:53.888+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:29:53.888+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T18:29:53.889+0200] {logging_mixin.py:190} INFO - [2025-02-28T18:29:53.888+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T18:29:53.889+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T18:29:53.924+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2025-02-28T20:11:39.021+0200] {processor.py:186} INFO - Started process (PID=97417) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:11:39.022+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T20:11:39.022+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:11:39.022+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:11:39.063+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:11:39.063+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T20:11:39.063+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:11:39.063+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T20:11:39.064+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:11:39.094+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-28T20:13:26.867+0200] {processor.py:186} INFO - Started process (PID=98028) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:13:26.868+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T20:13:26.869+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:13:26.869+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:13:26.906+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:13:26.906+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T20:13:26.906+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:13:26.906+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T20:13:26.907+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:13:26.936+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-28T20:15:14.446+0200] {processor.py:186} INFO - Started process (PID=98444) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:15:14.448+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T20:15:14.448+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:15:14.448+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:15:14.491+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:15:14.490+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T20:15:14.491+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:15:14.491+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T20:15:14.491+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:15:14.526+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-02-28T20:17:50.990+0200] {processor.py:186} INFO - Started process (PID=99032) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:17:50.991+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T20:17:50.992+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:17:50.992+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:17:51.030+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:17:51.029+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T20:17:51.030+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:17:51.030+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T20:17:51.030+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:17:51.060+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-28T20:19:06.651+0200] {processor.py:186} INFO - Started process (PID=99395) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:19:06.652+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T20:19:06.653+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:19:06.653+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:19:06.691+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:19:06.691+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T20:19:06.692+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:19:06.692+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T20:19:06.692+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:19:06.722+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-28T20:20:57.233+0200] {processor.py:186} INFO - Started process (PID=99836) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:20:57.234+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T20:20:57.234+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:20:57.234+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:20:57.277+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:20:57.276+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T20:20:57.277+0200] {logging_mixin.py:190} INFO - [2025-02-28T20:20:57.277+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T20:20:57.277+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T20:20:57.308+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2025-02-28T21:28:19.780+0200] {processor.py:186} INFO - Started process (PID=5629) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:28:19.780+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:28:19.781+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:28:19.781+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:28:19.851+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:28:19.850+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:28:19.851+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:28:19.851+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:28:19.851+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:28:19.895+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2025-02-28T21:31:05.489+0200] {processor.py:186} INFO - Started process (PID=6273) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:31:05.490+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:31:05.490+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:31:05.490+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:31:05.531+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:31:05.530+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:31:05.531+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:31:05.531+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:31:05.531+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:31:05.562+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-28T21:32:53.048+0200] {processor.py:186} INFO - Started process (PID=6844) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:32:53.048+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:32:53.049+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:32:53.049+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:32:53.090+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:32:53.089+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:32:53.090+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:32:53.090+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:32:53.090+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:32:53.121+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-28T21:35:29.232+0200] {processor.py:186} INFO - Started process (PID=7499) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:35:29.233+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:35:29.234+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:35:29.233+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:35:29.271+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:35:29.271+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:35:29.271+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:35:29.271+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:35:29.271+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:35:29.301+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-28T21:37:27.992+0200] {processor.py:186} INFO - Started process (PID=7991) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:37:27.992+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:37:27.993+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:37:27.993+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:37:28.036+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:37:28.035+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:37:28.036+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:37:28.036+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:37:28.036+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:37:28.074+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-02-28T21:39:18.441+0200] {processor.py:186} INFO - Started process (PID=8416) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:39:18.442+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:39:18.443+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:39:18.443+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:39:18.481+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:39:18.480+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:39:18.481+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:39:18.481+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:39:18.481+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:39:18.511+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-28T21:44:03.288+0200] {processor.py:186} INFO - Started process (PID=9697) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:44:03.290+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T21:44:03.291+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:44:03.290+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:44:03.396+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:44:03.395+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T21:44:03.396+0200] {logging_mixin.py:190} INFO - [2025-02-28T21:44:03.396+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T21:44:03.396+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T21:44:03.478+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.194 seconds
[2025-02-28T22:28:21.248+0200] {processor.py:186} INFO - Started process (PID=18205) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:28:21.250+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:28:21.250+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:28:21.250+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:28:21.286+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:28:21.286+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:28:21.286+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:28:21.286+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:28:21.286+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:28:21.316+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-28T22:36:25.090+0200] {processor.py:186} INFO - Started process (PID=19863) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:36:25.091+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:36:25.092+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:36:25.092+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:36:25.127+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:36:25.127+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:36:25.128+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:36:25.128+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:36:25.128+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:36:25.157+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-28T22:38:39.543+0200] {processor.py:186} INFO - Started process (PID=20351) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:38:39.544+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:38:39.544+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:38:39.544+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:38:39.582+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:38:39.582+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:38:39.582+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:38:39.582+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:38:39.582+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:38:39.612+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-28T22:41:28.612+0200] {processor.py:186} INFO - Started process (PID=20908) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:41:28.613+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:41:28.613+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:41:28.613+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:41:28.649+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:41:28.649+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:41:28.649+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:41:28.649+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:41:28.649+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:41:28.679+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-28T22:43:57.146+0200] {processor.py:186} INFO - Started process (PID=21458) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:43:57.147+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:43:57.148+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:43:57.148+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:43:57.184+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:43:57.183+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:43:57.184+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:43:57.184+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:43:57.184+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:43:57.214+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-28T22:46:57.958+0200] {processor.py:186} INFO - Started process (PID=22063) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:46:57.959+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:46:57.959+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:46:57.959+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:46:57.996+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:46:57.996+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:46:57.996+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:46:57.996+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:46:57.996+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:46:58.027+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-28T22:55:01.758+0200] {processor.py:186} INFO - Started process (PID=22782) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:55:01.760+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:55:01.761+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:55:01.761+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:55:01.798+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:55:01.797+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:55:01.798+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:55:01.798+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:55:01.798+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:55:01.827+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2025-02-28T22:56:57.643+0200] {processor.py:186} INFO - Started process (PID=23155) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:56:57.645+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:56:57.645+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:56:57.645+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:56:57.681+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:56:57.681+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:56:57.681+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:56:57.681+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:56:57.681+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:56:57.710+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-28T22:59:31.865+0200] {processor.py:186} INFO - Started process (PID=23654) to work on /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:59:31.866+0200] {processor.py:914} INFO - Processing file /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-28T22:59:31.866+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:59:31.866+0200] {dagbag.py:588} INFO - Filling up the DagBag from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:59:31.902+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:59:31.901+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-28T22:59:31.902+0200] {logging_mixin.py:190} INFO - [2025-02-28T22:59:31.902+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-28T22:59:31.902+0200] {processor.py:927} WARNING - No viable dags retrieved from /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-28T22:59:31.931+0200] {processor.py:208} INFO - Processing /Users/nampham/.pyenv/versions/3.12.9/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
